import { createSlice } from "@reduxjs/toolkit";

//Creating slice
const SearchResultSlice = createSlice({
    name: 'searchResults',
    initialState: [],
    reducers: {
        setSearchResults: (state, action) => {
            return action.payload;
        },
    },
});

// Extracting the 'setSearchResults' action creator from the slice
export const { setSearchResults } = SearchResultSlice.actions;

// Exporting the reducer function generated by the slice
export default SearchResultSlice.reducer;