import { createSlice } from "@reduxjs/toolkit";

//Creating slice
const headerSortSlice = createSlice({
    name: 'headerSort',
    initialState: { selectedSort: "hot"},
    reducers: {
        setHeaderSort: (state, action) => {
            // The reducer takes the current state and an action, and modifies the state
            state.selectedSort = action.payload;
        },
    },
});

// Extracting the 'setHeaderSort' action creator from the slice
export const { setHeaderSort } = headerSortSlice.actions;

// Selecting the 'selectedSort' property from the state
export const selectSortOption = (state) => state.sorting.selectedSort;

// Exporting the reducer function generated by the slice
export default headerSortSlice.reducer;