import { createSlice } from "@reduxjs/toolkit";

//Creating slice
const errorStateSlice = createSlice({
  name: 'errorState',
  initialState: false,
  reducers: {
    setErrorState: (state, action) => {
      // The reducer takes the current state and an action, and returns the new state
      return action.payload;
    },
  },
});

// Extracting the 'setErrorState' action creator from the slice
export const { setErrorState } = errorStateSlice.actions;

// Exporting the reducer function generated by the slice
export default errorStateSlice.reducer;